apiVersion: v1
kind: Service
metadata:
  name: personal-page-service
  namespace: personal-page
spec:
  selector:
    app: personal-page
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP